# Generated by Django 4.2.7 on 2023-11-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_name", models.CharField(max_length=255)),
                ("doc_spec", models.CharField(max_length=255)),
                ("doc_image", models.ImageField(upload_to="doctors")),
                (
                    "doc_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.departments",
                    ),
                ),
            ],
        ),
    ]
